In [1]:
import pandas as pd
import numpy as np
from math import sqrt
import sqlite3
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
import pickle

In [2]:
con = sqlite3.connect("./movies2.db")

In [3]:
features = pd.read_sql("SELECT * FROM features", con, index_col=None)
features

index     id                  title        open  nation  grade  genre  \
0         0  00000                   국제시장  2014-12-17       4      0      6   
1         1  00001                  테이큰 3  2015-01-01       1      1     14   
2         2  00002              마다가스카의 펭귄  2014-12-31       1      3     13   
3         3  00003        님아, 그 강을 건너지 마오  2014-11-27       4      3      5   
4         4  00004                   언브로큰  2015-01-07       1      1     14   
5         5  00005                    패딩턴  2015-01-07       1      3     17   
6         6  00006                   기술자들  2014-12-24       4      1     10   
7         7  00007                    워킹걸  2015-01-07       4      4     17   
8         8  00008           호빗: 다섯 군대 전투  2014-12-17       1      0     15   
9         9  00009                타임 패러독스  2015-01-07       1      1      0   
10       10  00010                  인터스텔라  2014-11-06       1      0      0   
11       11  00011                아메리칸 셰프  2015-01-07       1      1     17   
12       12  00012          개를 훔치는 완벽한 방법  2014-12-31       4      3      6   
13       13  00013      눈의 여왕 2: 트롤의 마법거울  2014-12-24       1      3     13   
14       14  00014                    상의원  2014-12-24       4      1     11   
15       15  00015              내일을 위한 시간  2015-01-01       1      0      6   
16       16  00016                  일곱난쟁이  2014-12-24       1      3     13   
17       17  00017                 오늘의 연애  2015-01-14       4      1      7   
18       18  00018                    허삼관  2015-01-14       4      0      6   
19       19  00021                     마미  2014-12-18       1      1      6   
20       20  00022     박물관이 살아있다 : 비밀의 무덤  2015-01-14       1      3     15   
21       21  00030                 유아 낫 유  2015-01-21       1      1      6   
22       22  00031                더 이퀄라이저  2015-01-28       1      4     14   
23       23  00032                   쿼바디스  2014-12-10       4      0      5   
24       24  00033                강남 1970  2015-01-21       4      4     14   
25       25  00034                    존 윅  2015-01-21       1      4     14   
26       26  00037              아메리칸 스나이퍼  2015-01-14       1      4     14   
27       27  00040                    와일드  2015-01-22       1      4      6   
28       28  00042         그 사람 그 사랑 그 세상  2014-11-20       4      3      5   
29       29  00051                  빅 히어로  2015-01-21       1      3     13   
...     ...    ...                    ...         ...     ...    ...    ...   
1141   1141  11355                    아일라  2018-06-21       1      1      6   
1142   1142  11356           바르다가 사랑한 얼굴들  2018-06-14       1      3      5   
1143   1143  11358             빅샤크: 매직체인지  2018-06-27       3      3     13   
1144   1144  11427      토니스토리2: 고철왕국의 친구들  2018-06-13       1      3     13   
1145   1145  11428                     마녀  2018-06-27       4      1      9   
1146   1146  11430      유니콘 원정대: 비밀의 다이어리  2018-06-21       0      3     13   
1147   1147  11432                  오 루시!  2018-06-28       1      1      7   
1148   1148  11473        시카리오: 데이 오브 솔다도  2018-06-27       1      1     14   
1149   1149  11478                 리틀 맨하탄  2018-06-27       1      3      7   
1150   1150  11538               앤트맨과 와스프  2018-07-04       1      0     14   
1151   1151  11540    이별의 아침에 약속의 꽃을 장식하자  2018-07-19       2      0     13   
1152   1152  11544             잉글랜드 이즈 마인  2018-07-05       1      0      6   
1153   1153  11628                스카이스크래퍼  2018-07-11       1      0     14   
1154   1154  11629                   속닥속닥  2018-07-13       4      1      3   
1155   1155  11631                인크레더블 2  2018-07-18       1      3     13   
1156   1156  11636                   서버비콘  2018-07-12       1      1     10   
1157   1157  11637   꼬마 보트 토토: 타요 타요 배 타요  2018-07-12       1      3     13   
1158   1158  11687           미션 임파서블: 폴아웃  2018-07-25       1      1     14   
1159   1159  11695  신비아파트: 금빛 도깨비와 비밀의 동굴  2018-07-25   

In [4]:
start_date = '2015-01-07'
end_date = '2018-06-30'
features_20150101_20180630 = features[features['open'] >= start_date]
features_20150101_20180630 = features_20150101_20180630[features['open'] <= end_date]


C:\Users\gudrb\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  after removing the cwd from sys.path.
C:\Users\gudrb\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """


In [5]:
from datetime import datetime,timedelta
from pandas import Series, DataFrame
def convert(s):
    return datetime.strptime(s, '%Y-%m-%d').date()
 

In [13]:
# for rows in features_20150101_20180630.iterrows():
#     tmp = pd.read_sql("SELECT * FROM "+ "'" +rows[1][1]+ "'", con, index_col=None)

In [14]:
# now = convert(rows[1][3])
# L=[]
# L=pd.date_range(start = now - timedelta(days=23),end= now + timedelta(days=23))

# df = pd.DataFrame(index=range(47))
# df[:]=0
# df['date']=L.strftime("%Y-%m-%d")
# df.set_index(df['date'], inplace=True)
# # del df['date']

# tmp.set_index(tmp['date'], inplace=True)

# # df_merged = pd.concat([df,tmp], axis=1)
# df_merged = pd.merge(df,tmp, how="outer")
# df_merged.isnull()
# # df_merged

# df_merged[df_merged.isnull()] = 0
# df_merged

In [16]:
cnt = 0

dataX = []
dataY = []
for rows in features_20150101_20180630.iterrows():
    tmp = pd.read_sql("SELECT * FROM "+ "'" +rows[1][1]+ "'", con, index_col=None)
    tmp.drop_duplicates(['date'], inplace=True)
    
    now = convert(rows[1][3])
    L=[]
    L=pd.date_range(start = now - timedelta(days=23),end= now + timedelta(days=23))

    df = pd.DataFrame(index=range(47))
    df[:]="0"
    df['date']=L.strftime("%Y-%m-%d")
    df.set_index(df['date'], inplace=True)
    
    tmp.set_index(tmp['date'], inplace=True)
    tmp=tmp[tmp['date']<(convert(rows[1][3])+ timedelta(days=24)).strftime("%Y-%m-%d")]
    tmp=tmp[tmp['date']>(convert(rows[1][3])- timedelta(days=24)).strftime("%Y-%m-%d")]

    df_merged = pd.merge(df,tmp, how="outer")
    df_merged.isnull()
    # df_merged

    df_merged[df_merged.isnull()] = 0
#     del df
    
#     df_merged['audience'] = np.array(pd.to_numeric(df_merged['audience'].str.replace(',',''), errors='coerce', downcast='float').tolist()).reshape(-1,1)
#     df_merged['play'] = np.array(pd.to_numeric(df_merged['play'].str.replace(',',''), errors='coerce', downcast='float').tolist()).reshape(-1,1)
    df_merged['audience'] = pd.to_numeric(df_merged['audience'].str.replace(',',''), errors='coerce', downcast='float')
    df_merged['play'] = pd.to_numeric(df_merged['play'].str.replace(',',''), errors='coerce', downcast='float')
    df_merged['director'] = rows[1][7]
    df_merged=df_merged.fillna(0) # nan값 0으로

    a_tmp = np.concatenate((df_merged['audience'],[0],df_merged['play'],[0],df_merged['director'],[0])).reshape((3,-1)).T

        
        #     a_tmp = MinMaxScaler(a_tmp)
    dataX.append(a_tmp)
    dataY.append([float(rows[1][9])])

#     cnt += 1
#     if cnt>1:
#         break

In [17]:
dataX = np.array(dataX)
dataY = np.array(dataY)
dataX

array([[[0.000000e+00, 0.000000e+00, 1.313540e+05],
        [0.000000e+00, 0.000000e+00, 1.313540e+05],
        [0.000000e+00, 0.000000e+00, 1.313540e+05],
        ...,
        [8.000000e+01, 1.000000e+00, 1.313540e+05],
        [7.500000e+01, 1.000000e+00, 1.313540e+05],
        [0.000000e+00, 0.000000e+00, 0.000000e+00]],

       [[0.000000e+00, 0.000000e+00, 3.270090e+05],
        [0.000000e+00, 0.000000e+00, 3.270090e+05],
        [0.000000e+00, 0.000000e+00, 3.270090e+05],
        ...,
        [2.300000e+02, 4.000000e+00, 3.270090e+05],
        [2.800000e+01, 1.000000e+00, 3.270090e+05],
        [0.000000e+00, 0.000000e+00, 0.000000e+00]],

       [[0.000000e+00, 0.000000e+00, 1.107548e+06],
        [0.000000e+00, 0.000000e+00, 1.107548e+06],
        [0.000000e+00, 0.000000e+00, 1.107548e+06],
        ...,
        [2.800000e+01, 4.000000e+00, 1.107548e+06],
        [4.300000e+01, 6.000000e+00, 1.107548e+06],
        [0.000000e+00, 0.000000e+00, 0.000000e+00]],

       ...,

      

In [8]:
# dataX = dataX.reshape(-1, 3)

In [33]:
dataX.shape

(1013, 48, 3)

In [ ]:
# min_max_scaler=MinMaxScaler()
# a,d,_ = np.split(dataX, [2,3], axis=1)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       ...,
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
# X_MinMax_train_a = min_max_scaler.fit_transform(a)
# X_MinMax_train_d = min_max_scaler.fit_transform(d)

# dataX_ = np.hstack((X_MinMax_train_a, X_MinMax_train_d))
# dataX = dataX_.reshape(-1, 48, 3)

In [10]:
# norm_dataX = []

# for data in dataX:
#     norm_dataX.append(data[0:-1])


In [ ]:
# scaler = MinMaxScaler(feature_range=(0,1))
# scaler_arr = []
# # scaler = scaler.fit(dataX_re.reshape(-1, 3))
# for i, x in enumerate(dataX):
#     scaler=scaler.fit(x)
#     scaler_arr.append(scaler.data_max_)
# print(scaler_arr)
# # dataX = np.vstack([np.expand_dims(1013,48) for x in dataX])

In [18]:
scaler = MinMaxScaler(feature_range=(0,1))
scaler = scaler.fit(dataX.reshape(-1, 3))

In [36]:
scaler_arr = []
norm_dataX = []
for i in dataX:
#     scaler = scaler.fit(i)
    scaler_arr.append(scaler.data_max_)
    norm_dataX.append(scaler.transform(i)[:47])

In [37]:
norm_dataX=np.array(norm_dataX)
norm_dataX.shape

(1013, 47, 3)

In [38]:
for i in range(10):
    plt.plot(norm_dataX[i][:,0])

In [39]:
plt.hist(dataY)

(array([805.,  70.,  40.,  22.,  20.,  23.,  12.,  11.,   4.,   6.]),
 array([  10052. ,  506020.3, 1001988.6, 1497956.9, 1993925.2, 2489893.5,
        2985861.8, 3481830.1, 3977798.4, 4473766.7, 4969735. ]),
 <a list of 10 Patch objects>)

In [40]:
scalerY = MinMaxScaler(feature_range=(0,1))
scalerY = scalerY.fit(dataY)
norm_dataY = scalerY.transform(dataY)
print(norm_dataY.min())
print(norm_dataY.max())

scalerfile = 'scalerY.sav'
pickle.dump(scalerY, open(scalerfile, 'wb'))

0.0
1.0


In [41]:
plt.hist(norm_dataY)

(array([805.,  70.,  40.,  22.,  20.,  23.,  12.,  11.,   4.,   6.]),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]),
 <a list of 10 Patch objects>)

In [42]:
scalerSY = StandardScaler()
sclaerSY = scalerSY.fit(norm_dataY)
print('Mean: %f, StandardDeviation: %f' % (scalerSY.mean_, sqrt(scalerSY.var_)))
stand_dataY = scalerSY.transform(norm_dataY)

Mean: 0.086761, StandardDeviation: 0.172113


In [43]:
plt.hist(stand_dataY)
print(stand_dataY.min())
print(stand_dataY.max())

-0.504094581487018
5.3060334330369505


In [44]:
np.save('./dataX.npy', norm_dataX)
np.save('./dataY.npy', norm_dataY)